Exception: fix error message on save
When an exception is thrown inside a save method, on the exception
created to rethrow it, we now prevent the message to be prefixed by the
exception class name so it can be displayed to the user.
RM47077